# Site settings
title: EveryWAN
email: franclombardo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  EveryWAN 
  open source SD-WAN for everyone
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://everywan.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  everywan-io

# Build settings
markdown: kramdown


paginate: 3
paginate_path: "blog/page:num"